# Generated by Django 5.0.6 on 2024-10-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('added', 'Добавлена'), ('in_progress', 'В работе'), ('completed', 'Выполнена')], default='added', max_length=20)),
            ],
        ),
    ]
